// import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Шифр Хилла',
    // description: 'Generated by create next app',
}

export default function HillCipherLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return <div>{children}</div>
}